name: infra

on:
  push:
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/infra.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: infra-${{ github.ref }}
  cancel-in-progress: false

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      TF_VAR_prefix: swewts
      TF_VAR_location: "Sweden Central"
      TF_VAR_rg_name: fh-wts-project
      TF_VAR_acr_name: acrswewts
      TF_VAR_kv_name: kv-swe-wts
      TF_VAR_sa_name: saswewtsz1
      TF_VAR_cae_name: cae-swe-wts
      TF_VAR_ca_name: ca-swe-wts-backend
      TF_VAR_existing_rg_name: fh-manuals
      TF_VAR_mi_name: mi-fh-projects-github
      TF_VAR_sql_server_name: sql-swe-wts
      TF_VAR_sql_database_name: wts-project-db
      TF_VAR_sql_admin_username: sqladmin
      TF_VAR_allowed_origins: '["https://saswewtsz1.z1.web.core.windows.net"]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Ensure tfstate container exists
        run: |
          az storage container create --name wts-project-tfstate --account-name terraformmanuals || true

      - name: Terraform init
        working-directory: infra
        run: terraform init -backend-config=backend.tfvars

      - name: Terraform fmt
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: infra
        run: terraform validate

      - name: Terraform plan
        id: plan
        working-directory: infra
        run: terraform plan -out=tf.plan

      - name: Upload plan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tf-plan
          path: infra/tf.plan
          if-no-files-found: warn
          retention-days: 7

      - name: Terraform apply
        working-directory: infra
        run: terraform apply -auto-approve tf.plan
